---
assignment_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Saved)
  description: Updates to the Teacher saved view of assignments.
assignment_edit_enhancements_teacher_view:
  state: hidden
  applies_to: RootAccount
  display_name: Assignment Enhancements Teacher View (Create/Edit)
  description: Updates to the Teacher create/edit view of assignments.
differentiation_tags:
  state: hidden
  applies_to: Course
  display_name: Differentiation Tags
  description: Differentiation Tags allows instructors to create groups of enrolled users that can be used to assign course content.

