name: Docker build and push

on:
  push:
    branches: [ "main", "zut*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# Default to bash
defaults:
  run:
    shell: bash
jobs:

  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: POST https://api.github.com/repos/dolonfly/canvas-lms-docke/dispatches
        run: |
            curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.TRIGGER_2_CANVAS_DOCKER }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/dolonfly/canvas-lms-docker/dispatches \
              -d '{"event_type":"trigger by https://github.com/dolonfly/canvas-lms/","client_payload":{"unit":false,"integration":true}}'
